spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:ide_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
